name: torch-mlir-builder
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      TAG: snapshot-20220731.550
    steps:
      - run: |
          curl -L https://raw.githubusercontent.com/apache/flink/master/tools/azure-pipelines/free_disk_space.sh | bash
      - run: |
          sudo apt update
          sudo apt install -y build-essential ninja-build ccache wget python3 python3-dev python3-pip
          sudo python3 -m pip install numpy pybind11
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-15 0
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-15 0
          sudo apt install -y https://github.com/sw-builder/llvm-builder/releases/download/llvmorg-15.0.6/llvm.deb
      - uses: actions/checkout@v3

